[package]
name = "gpxstat"
version = "1.2.0"
authors = ["Bill Fraser <wfraser@codewise.org>"]
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.0.32", features = ["cargo", "derive"] }
strong-xml = "0.6.2"
time = { version = "0.3", features = ["parsing"] }
