[package]
name = "gpxstat"
version = "1.1.2"
authors = ["Bill Fraser <wfraser@codewise.org>"]
edition = "2021"

[dependencies]
anyhow = "1"
strong-xml = "0.6.2"
structopt = "0.3"
time = { version = "0.3", features = ["parsing"] }
